name: flutter_adyen_cse_example
description: Demonstrates how to use the flutter_adyen_cse plugin.
publish_to: "none"

environment:
  sdk: "<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_adyen_cse:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
